name: nabeey
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Utility packages
  http: ^1.3.0
  intl: ^0.20.2
  lottie: ^3.3.1
  shimmer: ^3.0.0
  logger: ^2.5.0
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  connectivity_plus: ^6.1.3
  flutter_native_splash: ^2.4.5

  # Dependency Injection
  get_it: ^8.0.3

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  
  # Product Specific
  bloc: ^9.0.0
  hive: ^2.2.3
  readmore: ^3.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  audioplayers: ^6.4.0
  icons_flutter: ^0.0.5
  path_provider: ^2.1.5
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1
  expansion_tile_group: ^2.2.0
  youtube_player_flutter: ^9.1.1
  syncfusion_flutter_pdfviewer: ^29.1.35
  flutter_secure_storage: ^9.2.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.15
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/pdf/
    - assets/fonts/
    - .env
  #   - assets/fonts/sf-pro-display.ttf
    

  # fonts:
  #   - family: SFProDisplay